apiVersion: apps/v1
kind: Deployment
metadata:
  name: &app nlp-server
  namespace: mlops
  labels:
    app: *app
spec:
  selector:
    matchLabels:
      app: *app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 50%
  template:
    metadata:
      labels:
        app: *app
    spec:
      containers:
      - name: server
        image: nkostoulas/nlp-server:0.1
        ports:
        - containerPort: 8001
          name: http
