---
kind: HorizontalPodAutoscaler
apiVersion: autoscaling/v2
metadata:
  name: nlp-server-hpa
  namespace: mlops
  labels:
    app: nlp-server
spec:
  maxReplicas: 10
  minReplicas: 2
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80
  scaleTargetRef:
    kind: Deployment
    apiVersion: apps/v1
    name: nlp-server
